name: build

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - ".github/**.md"
      - "docs/**"
      - "tools/**"
      - "README.md"
      - "README_zh-CN.md"

  pull_request:
    branches:
      - "master"
    paths-ignore:
      - ".github/**.md"
      - "docs/**"
      - "tools/**"
      - "README.md"
      - "README_zh-CN.md"

permissions:
  contents: read

jobs:
  test_zetton_stream_gst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone dependencies on the same level
        run: |
          git clone https://github.com/project-zetton/zetton-common.git ../zetton-common
          git clone https://github.com/project-zetton/zetton-stream.git ../zetton-stream
          git clone https://github.com/project-zetton/zetton-docker.git ../zetton-docker
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libopencv-dev \
            libfmt-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-doc \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-qt5 \
            gstreamer1.0-pulseaudio \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-good1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            libgstrtspserver-1.0-dev
      - name: Install other dependencies
        run: |
          sudo ../zetton-docker/deps/install_absl.sh
          sudo ../zetton-docker/deps/install_catch2.sh
      - name: Install colcon
        run: |
          sudo apt-get install -y python3 python3-pip
          sudo python3 -m pip install -U colcon-common-extensions
      - name: Build
        run: |
          cd ..
          colcon build --packages-up-to ubis_cpp --cmake-args -DCMAKE_BUILD_TYPE=Release
      # - name: Test
      #   run: |
      #     colcon test --packages-select ubis_cpp --return-code-on-test-failure
      #     colcon test-result --verbose
